### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ddugovic** [akicho8/shogi_web#24]
Are other developers allowed to copy and modify shogi_web?
https://opensource.org/licenses

**Comment by akicho8** [comment]
For Shogi Wars game record search, because it takes a load on the upstream of shogi Wars in the other, we are concerned.
What is the use of shogi_web specifically?

**Comment by ddugovic** [comment]
Ah, very good point.  I am developing open source shogi software to help analyze games & train beginners such as myself, while also respecting rate limits, etc. for existing sites.  Perhaps later I will have a better focused question and can ask for a less permissive license, thanks.

Currently I am collaborating on:
* https://github.com/Tellmarch/playshogi
* https://github.com/ddugovic/python-shogi and https://github.com/ddugovic/python-chess-annotator/tree/shogi
* https://github.com/ddugovic/capablanca (ICS with partial shogi support)
